sonar.projectKey=raviteja081295_TinderApp
sonar.organization=raviteja081295

sonar.projectBaseDir=.

sonar.sources=.
sonar.tests=src

sonar.test.inclusions=src/**/*.test.js,src/**/*.test.jsx
sonar.exclusions=node_modules/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8