sonar.projectKey=raviteja081295_TinderApp
sonar.organization=raviteja081295

sonar.sources=src

sonar.exclusions=node_modules/**,coverage/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info

# 🔥 CRITICAL FIX
sonar.javascript.file.suffixes=.js,.jsx

sonar.sourceEncoding=UTF-8